data = {'FAM': [('RESN', (0, 1)),
         ('HUSB', (0, 1)),
         ('WIFE', (0, 1)),
         ('NCHI', (0, 1)),
         ('RIN', (0, 1)),
         ('CHAN', (0, 1))],
 'FAM.ANUL': [('HUSB', (0, 1)),
              ('WIFE', (0, 1)),
              ('TYPE', (0, 1)),
              ('DATE', (0, 1))],
 'FAM.ANUL.HUSB': [('AGE', (1, 1))],
 'FAM.ANUL.WIFE': [('AGE', (1, 1))],
 'FAM.CENS': [('HUSB', (0, 1)),
              ('WIFE', (0, 1)),
              ('TYPE', (0, 1)),
              ('DATE', (0, 1))],
 'FAM.CENS.HUSB': [('AGE', (1, 1))],
 'FAM.CENS.WIFE': [('AGE', (1, 1))],
 'FAM.CHAN': [('DATE', (1, 1))],
 'FAM.CHAN.DATE': [('TIME', (0, 1))],
 'FAM.DIV': [('HUSB', (0, 1)),
             ('WIFE', (0, 1)),
             ('TYPE', (0, 1)),
             ('DATE', (0, 1))],
 'FAM.DIV.HUSB': [('AGE', (1, 1))],
 'FAM.DIV.WIFE': [('AGE', (1, 1))],
 'FAM.DIVF': [('HUSB', (0, 1)),
              ('WIFE', (0, 1)),
              ('TYPE', (0, 1)),
              ('DATE', (0, 1))],
 'FAM.DIVF.HUSB': [('AGE', (1, 1))],
 'FAM.DIVF.WIFE': [('AGE', (1, 1))],
 'FAM.ENGA': [('HUSB', (0, 1)),
              ('WIFE', (0, 1)),
              ('TYPE', (0, 1)),
              ('DATE', (0, 1))],
 'FAM.ENGA.HUSB': [('AGE', (1, 1))],
 'FAM.ENGA.WIFE': [('AGE', (1, 1))],
 'FAM.EVEN': [('HUSB', (0, 1)),
              ('WIFE', (0, 1)),
              ('TYPE', (0, 1)),
              ('DATE', (0, 1))],
 'FAM.EVEN.HUSB': [('AGE', (1, 1))],
 'FAM.EVEN.WIFE': [('AGE', (1, 1))],
 'FAM.MARB': [('HUSB', (0, 1)),
              ('WIFE', (0, 1)),
              ('TYPE', (0, 1)),
              ('DATE', (0, 1))],
 'FAM.MARB.HUSB': [('AGE', (1, 1))],
 'FAM.MARB.WIFE': [('AGE', (1, 1))],
 'FAM.MARC': [('HUSB', (0, 1)),
              ('WIFE', (0, 1)),
              ('TYPE', (0, 1)),
              ('DATE', (0, 1))],
 'FAM.MARC.HUSB': [('AGE', (1, 1))],
 'FAM.MARC.WIFE': [('AGE', (1, 1))],
 'FAM.MARL': [('HUSB', (0, 1)),
              ('WIFE', (0, 1)),
              ('TYPE', (0, 1)),
              ('DATE', (0, 1))],
 'FAM.MARL.HUSB': [('AGE', (1, 1))],
 'FAM.MARL.WIFE': [('AGE', (1, 1))],
 'FAM.MARR': [('HUSB', (0, 1)),
              ('WIFE', (0, 1)),
              ('TYPE', (0, 1)),
              ('DATE', (0, 1))],
 'FAM.MARR.HUSB': [('AGE', (1, 1))],
 'FAM.MARR.WIFE': [('AGE', (1, 1))],
 'FAM.MARS': [('HUSB', (0, 1)),
              ('WIFE', (0, 1)),
              ('TYPE', (0, 1)),
              ('DATE', (0, 1))],
 'FAM.MARS.HUSB': [('AGE', (1, 1))],
 'FAM.MARS.WIFE': [('AGE', (1, 1))],
 'FAM.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.REFN': [('TYPE', (0, 1))],
 'FAM.RESI': [('HUSB', (0, 1)),
              ('WIFE', (0, 1)),
              ('TYPE', (0, 1)),
              ('DATE', (0, 1))],
 'FAM.RESI.HUSB': [('AGE', (1, 1))],
 'FAM.RESI.WIFE': [('AGE', (1, 1))],
 'FAM.SLGS': [('DATE', (0, 1)),
              ('TEMP', (0, 1)),
              ('PLAC', (0, 1)),
              ('STAT', (0, 1))],
 'FAM.SLGS.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'FAM.SLGS.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.SLGS.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.SLGS.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'FAM.SLGS.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.SLGS.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.SLGS.STAT': [('DATE', (1, 1))],
 'FAM.SOUR': [('PAGE', (0, 1)),
              ('EVEN', (0, 1)),
              ('DATA', (0, 1)),
              ('QUAY', (0, 1)),
              ('QUAY', (0, 1))],
 'FAM.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.SOUR.OBJE': [('FILE', (1, None)),
                   ('TITL', (0, 1)),
                   ('FILE', (1, None)),
                   ('TITL', (0, 1))],
 'FAM.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'HEAD': [('SOUR', (1, 1)),
          ('DEST', (0, 1)),
          ('DATE', (0, 1)),
          ('SUBM', (1, 1)),
          ('SUBN', (0, 1)),
          ('FILE', (0, 1)),
          ('COPR', (0, 1)),
          ('GEDC', (1, 1)),
          ('CHAR', (1, 1)),
          ('LANG', (0, 1)),
          ('PLAC', (0, 1)),
          ('NOTE', (0, 1))],
 'HEAD.CHAR': [('VERS', (0, 1))],
 'HEAD.DATE': [('TIME', (0, 1))],
 'HEAD.GEDC': [('VERS', (1, 1)), ('FORM', (1, 1))],
 'HEAD.PLAC': [('FORM', (1, 1))],
 'HEAD.SOUR': [('VERS', (0, 1)),
               ('NAME', (0, 1)),
               ('CORP', (0, 1)),
               ('DATA', (0, 1))],
 'HEAD.SOUR.CORP': [('ADDR', (0, 1)),
                    ('PHON', (0, 1)),
                    ('EMAIL', (0, 1)),
                    ('FAX', (0, 1)),
                    ('WWW', (0, 1))],
 'HEAD.SOUR.CORP.ADDR': [('CONT', (0, 3)),
                         ('ADR1', (0, 1)),
                         ('ADR2', (0, 1)),
                         ('ADR3', (0, 1)),
                         ('CITY', (0, 1)),
                         ('STAE', (0, 1)),
                         ('POST', (0, 1)),
                         ('CTRY', (0, 1))],
 'HEAD.SOUR.DATA': [('DATE', (0, 1)), ('COPR', (0, 1))],
 'INDI': [('RESN', (0, 1)),
          ('SEX', (0, 1)),
          ('RFN', (0, 1)),
          ('AFN', (0, 1)),
          ('RIN', (0, 1)),
          ('CHAN', (0, 1))],
 'INDI.ASSO': [('RELA', (1, 1))],
 'INDI.ASSO.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.ASSO.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.ASSO.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.ASSO.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.ASSO.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.ASSO.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.BAPL': [('DATE', (0, 1)),
               ('TEMP', (0, 1)),
               ('PLAC', (0, 1)),
               ('STAT', (0, 1))],
 'INDI.BAPL.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.BAPL.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.BAPL.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.BAPL.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.BAPL.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.BAPL.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.BAPL.STAT': [('DATE', (1, 1))],
 'INDI.BIRT': [('TYPE', (0, 1)),
               ('DATE', (0, 1)),
               ('AGE', (0, 1)),
               ('FAMC', (0, 1))],
 'INDI.CAST': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'INDI.CHAN': [('DATE', (1, 1))],
 'INDI.CHAN.DATE': [('TIME', (0, 1))],
 'INDI.CHR': [('TYPE', (0, 1)),
              ('DATE', (0, 1)),
              ('AGE', (0, 1)),
              ('FAMC', (0, 1))],
 'INDI.CONL': [('DATE', (0, 1)),
               ('TEMP', (0, 1)),
               ('PLAC', (0, 1)),
               ('STAT', (0, 1))],
 'INDI.CONL.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.CONL.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.CONL.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.CONL.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.CONL.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.CONL.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.CONL.STAT': [('DATE', (1, 1))],
 'INDI.DSCR': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'INDI.EDUC': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'INDI.ENDL': [('DATE', (0, 1)),
               ('TEMP', (0, 1)),
               ('PLAC', (0, 1)),
               ('STAT', (0, 1))],
 'INDI.ENDL.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.ENDL.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.ENDL.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.ENDL.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.ENDL.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.ENDL.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.ENDL.STAT': [('DATE', (1, 1))],
 'INDI.FACT': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'INDI.FAMC': [('PEDI', (0, 1)), ('STAT', (0, 1))],
 'INDI.IDNO': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'INDI.NAME': [('TYPE', (0, 1)),
               ('NPFX', (0, 1)),
               ('GIVN', (0, 1)),
               ('NICK', (0, 1)),
               ('SPFX', (0, 1)),
               ('SURN', (0, 1)),
               ('NSFX', (0, 1)),
               ('NOTE', (0, 1)),
               ('NOTE', (0, 1)),
               ('SOUR', (0, 1)),
               ('SOUR', (0, 1))],
 'INDI.NAME.FONE': [('TYPE', (1, 1)),
                    ('NPFX', (0, 1)),
                    ('GIVN', (0, 1)),
                    ('NICK', (0, 1)),
                    ('SPFX', (0, 1)),
                    ('SURN', (0, 1)),
                    ('NSFX', (0, 1)),
                    ('NOTE', (0, 1)),
                    ('NOTE', (0, 1)),
                    ('SOUR', (0, 1)),
                    ('SOUR', (0, 1))],
 'INDI.NAME.FONE.NOTE': [('CONC', (0, 1)), ('CONT', (0, 1))],
 'INDI.NAME.FONE.SOUR': [('PAGE', (0, 1)),
                         ('EVEN', (0, 1)),
                         ('DATA', (0, 1)),
                         ('OBJE', (0, 1)),
                         ('OBJE', (0, 1)),
                         ('NOTE', (0, 1)),
                         ('NOTE', (0, 1)),
                         ('QUAY', (0, 1)),
                         ('CONC', (0, 1)),
                         ('CONT', (0, 1)),
                         ('TEXT', (0, 1)),
                         ('OBJE', (0, 1)),
                         ('OBJE', (0, 1)),
                         ('NOTE', (0, 1)),
                         ('NOTE', (0, 1)),
                         ('QUAY', (0, 1))],
 'INDI.NAME.FONE.SOUR.DATA': [('DATE', (0, 1)), ('TEXT', (0, 1))],
 'INDI.NAME.FONE.SOUR.DATA.TEXT': [('CONC', (0, 1)), ('CONT', (0, 1))],
 'INDI.NAME.FONE.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.NAME.FONE.SOUR.NOTE': [('CONC', (0, 1)),
                              ('CONT', (0, 1)),
                              ('CONC', (0, 1)),
                              ('CONT', (0, 1))],
 'INDI.NAME.FONE.SOUR.OBJE': [('FILE', (0, 1)),
                              ('TITL', (0, 1)),
                              ('FILE', (0, 1)),
                              ('TITL', (0, 1))],
 'INDI.NAME.FONE.SOUR.OBJE.FILE': [('FORM', (0, 1)), ('FORM', (0, 1))],
 'INDI.NAME.FONE.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.NAME.FONE.SOUR.TEXT': [('CONC', (0, 1)), ('CONT', (0, 1))],
 'INDI.NAME.NOTE': [('CONC', (0, 1)), ('CONT', (0, 1))],
 'INDI.NAME.ROMN': [('TYPE', (1, 1)),
                    ('NPFX', (0, 1)),
                    ('GIVN', (0, 1)),
                    ('NICK', (0, 1)),
                    ('SPFX', (0, 1)),
                    ('SURN', (0, 1)),
                    ('NSFX', (0, 1)),
                    ('NOTE', (0, 1)),
                    ('NOTE', (0, 1)),
                    ('SOUR', (0, 1)),
                    ('SOUR', (0, 1))],
 'INDI.NAME.ROMN.NOTE': [('CONC', (0, 1)), ('CONT', (0, 1))],
 'INDI.NAME.ROMN.SOUR': [('PAGE', (0, 1)),
                         ('EVEN', (0, 1)),
                         ('DATA', (0, 1)),
                         ('OBJE', (0, 1)),
                         ('OBJE', (0, 1)),
                         ('NOTE', (0, 1)),
                         ('NOTE', (0, 1)),
                         ('QUAY', (0, 1)),
                         ('CONC', (0, 1)),
                         ('CONT', (0, 1)),
                         ('TEXT', (0, 1)),
                         ('OBJE', (0, 1)),
                         ('OBJE', (0, 1)),
                         ('NOTE', (0, 1)),
                         ('NOTE', (0, 1)),
                         ('QUAY', (0, 1))],
 'INDI.NAME.ROMN.SOUR.DATA': [('DATE', (0, 1)), ('TEXT', (0, 1))],
 'INDI.NAME.ROMN.SOUR.DATA.TEXT': [('CONC', (0, 1)), ('CONT', (0, 1))],
 'INDI.NAME.ROMN.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.NAME.ROMN.SOUR.NOTE': [('CONC', (0, 1)),
                              ('CONT', (0, 1)),
                              ('CONC', (0, 1)),
                              ('CONT', (0, 1))],
 'INDI.NAME.ROMN.SOUR.OBJE': [('FILE', (0, 1)),
                              ('TITL', (0, 1)),
                              ('FILE', (0, 1)),
                              ('TITL', (0, 1))],
 'INDI.NAME.ROMN.SOUR.OBJE.FILE': [('FORM', (0, 1)), ('FORM', (0, 1))],
 'INDI.NAME.ROMN.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.NAME.ROMN.SOUR.TEXT': [('CONC', (0, 1)), ('CONT', (0, 1))],
 'INDI.NAME.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('OBJE', (0, 1)),
                    ('OBJE', (0, 1)),
                    ('NOTE', (0, 1)),
                    ('NOTE', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('CONC', (0, 1)),
                    ('CONT', (0, 1)),
                    ('TEXT', (0, 1)),
                    ('OBJE', (0, 1)),
                    ('OBJE', (0, 1)),
                    ('NOTE', (0, 1)),
                    ('NOTE', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.NAME.SOUR.DATA': [('DATE', (0, 1)), ('TEXT', (0, 1))],
 'INDI.NAME.SOUR.DATA.TEXT': [('CONC', (0, 1)), ('CONT', (0, 1))],
 'INDI.NAME.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.NAME.SOUR.NOTE': [('CONC', (0, 1)),
                         ('CONT', (0, 1)),
                         ('CONC', (0, 1)),
                         ('CONT', (0, 1))],
 'INDI.NAME.SOUR.OBJE': [('FILE', (0, 1)),
                         ('TITL', (0, 1)),
                         ('FILE', (0, 1)),
                         ('TITL', (0, 1))],
 'INDI.NAME.SOUR.OBJE.FILE': [('FORM', (0, 1)), ('FORM', (0, 1))],
 'INDI.NAME.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.NAME.SOUR.TEXT': [('CONC', (0, 1)), ('CONT', (0, 1))],
 'INDI.NATI': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'INDI.NCHI': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'INDI.NMR': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'INDI.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.OCCU': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'INDI.PROP': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'INDI.REFN': [('TYPE', (0, 1))],
 'INDI.RELI': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'INDI.RESI': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'INDI.SLGC': [('DATE', (0, 1)),
               ('TEMP', (0, 1)),
               ('PLAC', (0, 1)),
               ('FAMC', (1, 1)),
               ('STAT', (0, 1))],
 'INDI.SLGC.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.SLGC.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.SLGC.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.SLGC.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.SLGC.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.SLGC.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.SLGC.STAT': [('DATE', (1, 1))],
 'INDI.SOUR': [('PAGE', (0, 1)),
               ('EVEN', (0, 1)),
               ('DATA', (0, 1)),
               ('QUAY', (0, 1)),
               ('QUAY', (0, 1))],
 'INDI.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.SOUR.OBJE': [('FILE', (1, None)),
                    ('TITL', (0, 1)),
                    ('FILE', (1, None)),
                    ('TITL', (0, 1))],
 'INDI.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.SSN': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'INDI.TITL': [('TYPE', (0, 1)), ('DATE', (0, 1)), ('AGE', (0, 1))],
 'NOTE': [('RIN', (0, 1)), ('CHAN', (0, 1))],
 'NOTE.CHAN': [('DATE', (1, 1))],
 'NOTE.CHAN.DATE': [('TIME', (0, 1))],
 'NOTE.REFN': [('TYPE', (0, 1))],
 'NOTE.SOUR': [('PAGE', (0, 1)),
               ('EVEN', (0, 1)),
               ('DATA', (0, 1)),
               ('QUAY', (0, 1)),
               ('QUAY', (0, 1))],
 'NOTE.SOUR.DATA': [('DATE', (0, 1))],
 'NOTE.SOUR.EVEN': [('ROLE', (0, 1))],
 'NOTE.SOUR.OBJE': [('FILE', (1, None)),
                    ('TITL', (0, 1)),
                    ('FILE', (1, None)),
                    ('TITL', (0, 1))],
 'NOTE.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'NOTE.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'OBJE': [('FILE', (1, None)), ('RIN', (0, 1)), ('CHAN', (0, 1))],
 'OBJE.CHAN': [('DATE', (1, 1))],
 'OBJE.CHAN.DATE': [('TIME', (0, 1))],
 'OBJE.FILE': [('FORM', (1, 1)), ('TITL', (0, 1))],
 'OBJE.FILE.FORM': [('TYPE', (0, 1))],
 'OBJE.REFN': [('TYPE', (0, 1))],
 'OBJE.SOUR': [('PAGE', (0, 1)),
               ('EVEN', (0, 1)),
               ('DATA', (0, 1)),
               ('QUAY', (0, 1)),
               ('QUAY', (0, 1))],
 'OBJE.SOUR.DATA': [('DATE', (0, 1))],
 'OBJE.SOUR.EVEN': [('ROLE', (0, 1))],
 'OBJE.SOUR.OBJE': [('FILE', (1, None)),
                    ('TITL', (0, 1)),
                    ('FILE', (1, None)),
                    ('TITL', (0, 1))],
 'OBJE.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'OBJE.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'REPO': [('NAME', (1, 1)),
          ('ADDR', (0, 1)),
          ('PHON', (0, 1)),
          ('EMAIL', (0, 1)),
          ('FAX', (0, 1)),
          ('WWW', (0, 1)),
          ('RIN', (0, 1)),
          ('CHAN', (0, 1))],
 'REPO.ADDR': [('CONT', (0, 3)),
               ('ADR1', (0, 1)),
               ('ADR2', (0, 1)),
               ('ADR3', (0, 1)),
               ('CITY', (0, 1)),
               ('STAE', (0, 1)),
               ('POST', (0, 1)),
               ('CTRY', (0, 1))],
 'REPO.CHAN': [('DATE', (1, 1))],
 'REPO.CHAN.DATE': [('TIME', (0, 1))],
 'REPO.REFN': [('TYPE', (0, 1))],
 'SOUR': [('DATA', (0, 1)),
          ('AUTH', (0, 1)),
          ('TITL', (0, 1)),
          ('ABBR', (0, 1)),
          ('PUBL', (0, 1)),
          ('TEXT', (0, 1)),
          ('RIN', (0, 1)),
          ('CHAN', (0, 1))],
 'SOUR.CHAN': [('DATE', (1, 1))],
 'SOUR.CHAN.DATE': [('TIME', (0, 1))],
 'SOUR.DATA': [('AGNC', (0, 1))],
 'SOUR.DATA.EVEN': [('DATE', (0, 1)), ('PLAC', (0, 1))],
 'SOUR.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'SOUR.OBJE.FILE': [('FORM', (1, 1))],
 'SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'SOUR.REFN': [('TYPE', (0, 1))],
 'SOUR.REPO.CALN': [('MEDI', (0, 1))],
 'SUBM': [('NAME', (1, 1)),
          ('ADDR', (0, 1)),
          ('PHON', (0, 1)),
          ('EMAIL', (0, 1)),
          ('FAX', (0, 1)),
          ('WWW', (0, 1)),
          ('LANG', (0, 3)),
          ('RFN', (0, 1)),
          ('RIN', (0, 1)),
          ('CHAN', (0, 1))],
 'SUBM.ADDR': [('CONT', (0, 3)),
               ('ADR1', (0, 1)),
               ('ADR2', (0, 1)),
               ('ADR3', (0, 1)),
               ('CITY', (0, 1)),
               ('STAE', (0, 1)),
               ('POST', (0, 1)),
               ('CTRY', (0, 1))],
 'SUBM.CHAN': [('DATE', (1, 1))],
 'SUBM.CHAN.DATE': [('TIME', (0, 1))],
 'SUBM.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'SUBM.OBJE.FILE': [('FORM', (1, 1))],
 'SUBM.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'SUBN': [('SUBM', (0, 1)),
          ('FAMF', (0, 1)),
          ('TEMP', (0, 1)),
          ('ANCE', (0, 1)),
          ('DESC', (0, 1)),
          ('ORDI', (0, 1)),
          ('RIN', (0, 1)),
          ('CHAN', (0, 1))],
 'SUBN.CHAN': [('DATE', (1, 1))],
 'SUBN.CHAN.DATE': [('TIME', (0, 1))]}
