data = {'FAM': [('RESN', (0, 1)),
         ('HUSB', (0, 1)),
         ('WIFE', (0, 1)),
         ('NCHI', (0, 1)),
         ('RIN', (0, 1))],
 'FAM.ANUL.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'FAM.ANUL.HUSB': [('AGE', (1, 1))],
 'FAM.ANUL.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.ANUL.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.ANUL.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.ANUL.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'FAM.ANUL.PLAC.FONE': [('TYPE', (1, 1))],
 'FAM.ANUL.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'FAM.ANUL.PLAC.ROMN': [('TYPE', (1, 1))],
 'FAM.ANUL.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'FAM.ANUL.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.ANUL.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.ANUL.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'FAM.ANUL.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.ANUL.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.ANUL.WIFE': [('AGE', (1, 1))],
 'FAM.CENS.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'FAM.CENS.HUSB': [('AGE', (1, 1))],
 'FAM.CENS.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.CENS.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.CENS.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.CENS.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'FAM.CENS.PLAC.FONE': [('TYPE', (1, 1))],
 'FAM.CENS.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'FAM.CENS.PLAC.ROMN': [('TYPE', (1, 1))],
 'FAM.CENS.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'FAM.CENS.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.CENS.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.CENS.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'FAM.CENS.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.CENS.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.CENS.WIFE': [('AGE', (1, 1))],
 'FAM.CHAN': [('DATE', (1, 1))],
 'FAM.CHAN.DATE': [('TIME', (0, 1))],
 'FAM.DIV.ADDR': [('CONT', (0, 3)),
                  ('ADR1', (0, 1)),
                  ('ADR2', (0, 1)),
                  ('ADR3', (0, 1)),
                  ('CITY', (0, 1)),
                  ('STAE', (0, 1)),
                  ('POST', (0, 1)),
                  ('CTRY', (0, 1))],
 'FAM.DIV.HUSB': [('AGE', (1, 1))],
 'FAM.DIV.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.DIV.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.DIV.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.DIV.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'FAM.DIV.PLAC.FONE': [('TYPE', (1, 1))],
 'FAM.DIV.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'FAM.DIV.PLAC.ROMN': [('TYPE', (1, 1))],
 'FAM.DIV.SOUR': [('PAGE', (0, 1)),
                  ('EVEN', (0, 1)),
                  ('DATA', (0, 1)),
                  ('QUAY', (0, 1)),
                  ('QUAY', (0, 1))],
 'FAM.DIV.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.DIV.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.DIV.SOUR.OBJE': [('FILE', (1, None)),
                       ('TITL', (0, 1)),
                       ('FILE', (1, None)),
                       ('TITL', (0, 1))],
 'FAM.DIV.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.DIV.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.DIV.WIFE': [('AGE', (1, 1))],
 'FAM.DIVF.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'FAM.DIVF.HUSB': [('AGE', (1, 1))],
 'FAM.DIVF.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.DIVF.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.DIVF.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.DIVF.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'FAM.DIVF.PLAC.FONE': [('TYPE', (1, 1))],
 'FAM.DIVF.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'FAM.DIVF.PLAC.ROMN': [('TYPE', (1, 1))],
 'FAM.DIVF.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'FAM.DIVF.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.DIVF.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.DIVF.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'FAM.DIVF.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.DIVF.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.DIVF.WIFE': [('AGE', (1, 1))],
 'FAM.ENGA.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'FAM.ENGA.HUSB': [('AGE', (1, 1))],
 'FAM.ENGA.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.ENGA.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.ENGA.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.ENGA.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'FAM.ENGA.PLAC.FONE': [('TYPE', (1, 1))],
 'FAM.ENGA.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'FAM.ENGA.PLAC.ROMN': [('TYPE', (1, 1))],
 'FAM.ENGA.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'FAM.ENGA.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.ENGA.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.ENGA.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'FAM.ENGA.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.ENGA.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.ENGA.WIFE': [('AGE', (1, 1))],
 'FAM.EVEN.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'FAM.EVEN.HUSB': [('AGE', (1, 1))],
 'FAM.EVEN.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.EVEN.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.EVEN.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.EVEN.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'FAM.EVEN.PLAC.FONE': [('TYPE', (1, 1))],
 'FAM.EVEN.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'FAM.EVEN.PLAC.ROMN': [('TYPE', (1, 1))],
 'FAM.EVEN.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'FAM.EVEN.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.EVEN.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.EVEN.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'FAM.EVEN.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.EVEN.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.EVEN.WIFE': [('AGE', (1, 1))],
 'FAM.MARB.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'FAM.MARB.HUSB': [('AGE', (1, 1))],
 'FAM.MARB.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.MARB.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.MARB.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.MARB.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'FAM.MARB.PLAC.FONE': [('TYPE', (1, 1))],
 'FAM.MARB.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'FAM.MARB.PLAC.ROMN': [('TYPE', (1, 1))],
 'FAM.MARB.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'FAM.MARB.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.MARB.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.MARB.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'FAM.MARB.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.MARB.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.MARB.WIFE': [('AGE', (1, 1))],
 'FAM.MARC.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'FAM.MARC.HUSB': [('AGE', (1, 1))],
 'FAM.MARC.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.MARC.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.MARC.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.MARC.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'FAM.MARC.PLAC.FONE': [('TYPE', (1, 1))],
 'FAM.MARC.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'FAM.MARC.PLAC.ROMN': [('TYPE', (1, 1))],
 'FAM.MARC.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'FAM.MARC.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.MARC.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.MARC.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'FAM.MARC.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.MARC.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.MARC.WIFE': [('AGE', (1, 1))],
 'FAM.MARL.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'FAM.MARL.HUSB': [('AGE', (1, 1))],
 'FAM.MARL.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.MARL.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.MARL.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.MARL.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'FAM.MARL.PLAC.FONE': [('TYPE', (1, 1))],
 'FAM.MARL.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'FAM.MARL.PLAC.ROMN': [('TYPE', (1, 1))],
 'FAM.MARL.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'FAM.MARL.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.MARL.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.MARL.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'FAM.MARL.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.MARL.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.MARL.WIFE': [('AGE', (1, 1))],
 'FAM.MARR.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'FAM.MARR.HUSB': [('AGE', (1, 1))],
 'FAM.MARR.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.MARR.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.MARR.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.MARR.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'FAM.MARR.PLAC.FONE': [('TYPE', (1, 1))],
 'FAM.MARR.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'FAM.MARR.PLAC.ROMN': [('TYPE', (1, 1))],
 'FAM.MARR.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'FAM.MARR.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.MARR.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.MARR.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'FAM.MARR.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.MARR.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.MARR.WIFE': [('AGE', (1, 1))],
 'FAM.MARS.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'FAM.MARS.HUSB': [('AGE', (1, 1))],
 'FAM.MARS.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.MARS.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.MARS.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.MARS.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'FAM.MARS.PLAC.FONE': [('TYPE', (1, 1))],
 'FAM.MARS.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'FAM.MARS.PLAC.ROMN': [('TYPE', (1, 1))],
 'FAM.MARS.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'FAM.MARS.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.MARS.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.MARS.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'FAM.MARS.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.MARS.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.MARS.WIFE': [('AGE', (1, 1))],
 'FAM.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.REFN': [('TYPE', (0, 1))],
 'FAM.RESI.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'FAM.RESI.HUSB': [('AGE', (1, 1))],
 'FAM.RESI.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'FAM.RESI.OBJE.FILE': [('FORM', (1, 1))],
 'FAM.RESI.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'FAM.RESI.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'FAM.RESI.PLAC.FONE': [('TYPE', (1, 1))],
 'FAM.RESI.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'FAM.RESI.PLAC.ROMN': [('TYPE', (1, 1))],
 'FAM.RESI.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'FAM.RESI.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.RESI.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.RESI.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'FAM.RESI.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.RESI.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.RESI.WIFE': [('AGE', (1, 1))],
 'FAM.SLGS': [('DATE', (0, 1)),
              ('TEMP', (0, 1)),
              ('PLAC', (0, 1)),
              ('STAT', (0, 1))],
 'FAM.SLGS.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'FAM.SLGS.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.SLGS.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.SLGS.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'FAM.SLGS.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.SLGS.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'FAM.SLGS.STAT': [('DATE', (1, 1))],
 'FAM.SOUR': [('PAGE', (0, 1)),
              ('EVEN', (0, 1)),
              ('DATA', (0, 1)),
              ('QUAY', (0, 1)),
              ('QUAY', (0, 1))],
 'FAM.SOUR.DATA': [('DATE', (0, 1))],
 'FAM.SOUR.EVEN': [('ROLE', (0, 1))],
 'FAM.SOUR.OBJE': [('FILE', (1, None)),
                   ('TITL', (0, 1)),
                   ('FILE', (1, None)),
                   ('TITL', (0, 1))],
 'FAM.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'FAM.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'HEAD': [('SOUR', (1, 1)),
          ('DEST', (0, 1)),
          ('DATE', (0, 1)),
          ('SUBM', (1, 1)),
          ('SUBN', (0, 1)),
          ('FILE', (0, 1)),
          ('COPR', (0, 1)),
          ('GEDC', (1, 1)),
          ('CHAR', (1, 1)),
          ('LANG', (0, 1)),
          ('PLAC', (0, 1)),
          ('NOTE', (0, 1))],
 'HEAD.CHAR': [('VERS', (0, 1))],
 'HEAD.DATE': [('TIME', (0, 1))],
 'HEAD.GEDC': [('VERS', (1, 1)), ('FORM', (1, 1))],
 'HEAD.PLAC': [('FORM', (1, 1))],
 'HEAD.SOUR': [('VERS', (0, 1)),
               ('NAME', (0, 1)),
               ('CORP', (0, 1)),
               ('DATA', (0, 1))],
 'HEAD.SOUR.CORP.ADDR': [('CONT', (0, 3)),
                         ('ADR1', (0, 1)),
                         ('ADR2', (0, 1)),
                         ('ADR3', (0, 1)),
                         ('CITY', (0, 1)),
                         ('STAE', (0, 1)),
                         ('POST', (0, 1)),
                         ('CTRY', (0, 1))],
 'HEAD.SOUR.DATA': [('DATE', (0, 1)), ('COPR', (0, 1))],
 'INDI': [('RESN', (0, 1)),
          ('SEX', (0, 1)),
          ('RFN', (0, 1)),
          ('AFN', (0, 1)),
          ('RIN', (0, 1))],
 'INDI.ADOP': [('FAMC', (0, 1))],
 'INDI.ADOP.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.ADOP.FAMC': [('ADOP', (0, 1))],
 'INDI.ADOP.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.ADOP.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.ADOP.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.ADOP.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.ADOP.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.ADOP.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.ADOP.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.ADOP.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.ADOP.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.ADOP.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.ADOP.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.ADOP.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.ADOP.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.ASSO': [('RELA', (1, 1))],
 'INDI.ASSO.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.ASSO.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.ASSO.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.ASSO.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.ASSO.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.ASSO.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.BAPL': [('DATE', (0, 1)),
               ('TEMP', (0, 1)),
               ('PLAC', (0, 1)),
               ('STAT', (0, 1))],
 'INDI.BAPL.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.BAPL.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.BAPL.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.BAPL.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.BAPL.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.BAPL.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.BAPL.STAT': [('DATE', (1, 1))],
 'INDI.BAPM.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.BAPM.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.BAPM.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.BAPM.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.BAPM.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.BAPM.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.BAPM.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.BAPM.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.BAPM.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.BAPM.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.BAPM.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.BAPM.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.BAPM.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.BAPM.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.BARM.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.BARM.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.BARM.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.BARM.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.BARM.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.BARM.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.BARM.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.BARM.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.BARM.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.BARM.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.BARM.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.BARM.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.BARM.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.BARM.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.BASM.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.BASM.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.BASM.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.BASM.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.BASM.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.BASM.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.BASM.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.BASM.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.BASM.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.BASM.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.BASM.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.BASM.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.BASM.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.BASM.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.BIRT': [('FAMC', (0, 1))],
 'INDI.BIRT.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.BIRT.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.BIRT.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.BIRT.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.BIRT.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.BIRT.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.BIRT.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.BIRT.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.BIRT.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.BIRT.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.BIRT.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.BIRT.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.BIRT.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.BIRT.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.BLES.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.BLES.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.BLES.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.BLES.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.BLES.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.BLES.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.BLES.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.BLES.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.BLES.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.BLES.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.BLES.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.BLES.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.BLES.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.BLES.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.BURI.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.BURI.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.BURI.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.BURI.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.BURI.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.BURI.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.BURI.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.BURI.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.BURI.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.BURI.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.BURI.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.BURI.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.BURI.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.BURI.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.CAST.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.CAST.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.CAST.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.CAST.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.CAST.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.CAST.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.CAST.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.CAST.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.CAST.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.CAST.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.CAST.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.CAST.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.CAST.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.CAST.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.CENS.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.CENS.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.CENS.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.CENS.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.CENS.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.CENS.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.CENS.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.CENS.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.CENS.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.CENS.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.CENS.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.CENS.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.CENS.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.CENS.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.CHAN': [('DATE', (1, 1))],
 'INDI.CHAN.DATE': [('TIME', (0, 1))],
 'INDI.CHR': [('FAMC', (0, 1))],
 'INDI.CHR.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'INDI.CHR.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.CHR.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.CHR.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.CHR.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.CHR.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.CHR.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.CHR.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.CHR.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'INDI.CHR.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.CHR.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.CHR.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'INDI.CHR.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.CHR.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.CHRA.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.CHRA.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.CHRA.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.CHRA.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.CHRA.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.CHRA.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.CHRA.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.CHRA.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.CHRA.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.CHRA.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.CHRA.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.CHRA.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.CHRA.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.CHRA.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.CONF.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.CONF.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.CONF.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.CONF.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.CONF.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.CONF.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.CONF.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.CONF.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.CONF.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.CONF.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.CONF.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.CONF.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.CONF.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.CONF.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.CONL': [('DATE', (0, 1)),
               ('TEMP', (0, 1)),
               ('PLAC', (0, 1)),
               ('STAT', (0, 1))],
 'INDI.CONL.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.CONL.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.CONL.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.CONL.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.CONL.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.CONL.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.CONL.STAT': [('DATE', (1, 1))],
 'INDI.CREM.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.CREM.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.CREM.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.CREM.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.CREM.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.CREM.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.CREM.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.CREM.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.CREM.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.CREM.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.CREM.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.CREM.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.CREM.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.CREM.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.DEAT.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.DEAT.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.DEAT.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.DEAT.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.DEAT.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.DEAT.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.DEAT.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.DEAT.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.DEAT.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.DEAT.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.DEAT.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.DEAT.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.DEAT.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.DEAT.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.DSCR.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.DSCR.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.DSCR.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.DSCR.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.DSCR.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.DSCR.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.DSCR.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.DSCR.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.DSCR.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.DSCR.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.DSCR.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.DSCR.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.DSCR.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.DSCR.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.EDUC.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.EDUC.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.EDUC.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.EDUC.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.EDUC.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.EDUC.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.EDUC.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.EDUC.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.EDUC.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.EDUC.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.EDUC.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.EDUC.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.EDUC.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.EDUC.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.EMIG.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.EMIG.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.EMIG.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.EMIG.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.EMIG.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.EMIG.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.EMIG.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.EMIG.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.EMIG.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.EMIG.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.EMIG.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.EMIG.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.EMIG.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.EMIG.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.ENDL': [('DATE', (0, 1)),
               ('TEMP', (0, 1)),
               ('PLAC', (0, 1)),
               ('STAT', (0, 1))],
 'INDI.ENDL.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.ENDL.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.ENDL.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.ENDL.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.ENDL.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.ENDL.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.ENDL.STAT': [('DATE', (1, 1))],
 'INDI.EVEN.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.EVEN.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.EVEN.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.EVEN.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.EVEN.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.EVEN.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.EVEN.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.EVEN.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.EVEN.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.EVEN.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.EVEN.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.EVEN.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.EVEN.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.EVEN.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.FACT.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.FACT.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.FACT.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.FACT.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.FACT.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.FACT.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.FACT.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.FACT.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.FACT.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.FACT.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.FACT.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.FACT.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.FACT.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.FACT.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.FAMC': [('PEDI', (0, 1)), ('STAT', (0, 1))],
 'INDI.FCOM.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.FCOM.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.FCOM.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.FCOM.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.FCOM.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.FCOM.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.FCOM.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.FCOM.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.FCOM.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.FCOM.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.FCOM.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.FCOM.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.FCOM.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.FCOM.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.GRAD.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.GRAD.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.GRAD.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.GRAD.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.GRAD.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.GRAD.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.GRAD.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.GRAD.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.GRAD.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.GRAD.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.GRAD.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.GRAD.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.GRAD.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.GRAD.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.IDNO.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.IDNO.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.IDNO.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.IDNO.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.IDNO.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.IDNO.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.IDNO.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.IDNO.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.IDNO.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.IDNO.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.IDNO.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.IDNO.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.IDNO.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.IDNO.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.IMMI.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.IMMI.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.IMMI.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.IMMI.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.IMMI.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.IMMI.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.IMMI.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.IMMI.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.IMMI.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.IMMI.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.IMMI.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.IMMI.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.IMMI.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.IMMI.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.NAME': [('TYPE', (0, 1))],
 'INDI.NAME.FONE': [('TYPE', (1, 1))],
 'INDI.NAME.FONE.SOUR': [('PAGE', (0, 1)),
                         ('EVEN', (0, 1)),
                         ('DATA', (0, 1)),
                         ('QUAY', (0, 1)),
                         ('QUAY', (0, 1))],
 'INDI.NAME.FONE.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.NAME.FONE.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.NAME.FONE.SOUR.OBJE': [('FILE', (1, None)),
                              ('TITL', (0, 1)),
                              ('FILE', (1, None)),
                              ('TITL', (0, 1))],
 'INDI.NAME.FONE.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.NAME.FONE.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.NAME.ROMN': [('TYPE', (1, 1))],
 'INDI.NAME.ROMN.SOUR': [('PAGE', (0, 1)),
                         ('EVEN', (0, 1)),
                         ('DATA', (0, 1)),
                         ('QUAY', (0, 1)),
                         ('QUAY', (0, 1))],
 'INDI.NAME.ROMN.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.NAME.ROMN.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.NAME.ROMN.SOUR.OBJE': [('FILE', (1, None)),
                              ('TITL', (0, 1)),
                              ('FILE', (1, None)),
                              ('TITL', (0, 1))],
 'INDI.NAME.ROMN.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.NAME.ROMN.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.NAME.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.NAME.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.NAME.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.NAME.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.NAME.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.NAME.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.NATI.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.NATI.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.NATI.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.NATI.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.NATI.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.NATI.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.NATI.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.NATI.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.NATI.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.NATI.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.NATI.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.NATI.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.NATI.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.NATI.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.NATU.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.NATU.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.NATU.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.NATU.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.NATU.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.NATU.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.NATU.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.NATU.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.NATU.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.NATU.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.NATU.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.NATU.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.NATU.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.NATU.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.NCHI.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.NCHI.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.NCHI.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.NCHI.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.NCHI.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.NCHI.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.NCHI.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.NCHI.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.NCHI.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.NCHI.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.NCHI.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.NCHI.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.NCHI.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.NCHI.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.NMR.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'INDI.NMR.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.NMR.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.NMR.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.NMR.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.NMR.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.NMR.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.NMR.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.NMR.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'INDI.NMR.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.NMR.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.NMR.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'INDI.NMR.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.NMR.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.OCCU.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.OCCU.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.OCCU.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.OCCU.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.OCCU.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.OCCU.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.OCCU.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.OCCU.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.OCCU.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.OCCU.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.OCCU.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.OCCU.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.OCCU.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.OCCU.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.ORDN.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.ORDN.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.ORDN.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.ORDN.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.ORDN.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.ORDN.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.ORDN.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.ORDN.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.ORDN.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.ORDN.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.ORDN.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.ORDN.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.ORDN.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.ORDN.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.PROB.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.PROB.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.PROB.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.PROB.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.PROB.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.PROB.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.PROB.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.PROB.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.PROB.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.PROB.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.PROB.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.PROB.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.PROB.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.PROB.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.PROP.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.PROP.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.PROP.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.PROP.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.PROP.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.PROP.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.PROP.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.PROP.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.PROP.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.PROP.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.PROP.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.PROP.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.PROP.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.PROP.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.REFN': [('TYPE', (0, 1))],
 'INDI.RELI.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.RELI.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.RELI.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.RELI.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.RELI.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.RELI.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.RELI.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.RELI.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.RELI.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.RELI.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.RELI.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.RELI.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.RELI.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.RELI.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.RESI.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.RESI.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.RESI.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.RESI.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.RESI.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.RESI.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.RESI.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.RESI.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.RESI.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.RESI.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.RESI.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.RESI.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.RESI.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.RESI.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.RETI.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.RETI.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.RETI.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.RETI.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.RETI.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.RETI.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.RETI.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.RETI.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.RETI.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.RETI.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.RETI.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.RETI.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.RETI.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.RETI.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.SLGC': [('DATE', (0, 1)),
               ('TEMP', (0, 1)),
               ('PLAC', (0, 1)),
               ('FAMC', (1, 1)),
               ('STAT', (0, 1))],
 'INDI.SLGC.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.SLGC.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.SLGC.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.SLGC.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.SLGC.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.SLGC.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.SLGC.STAT': [('DATE', (1, 1))],
 'INDI.SOUR': [('PAGE', (0, 1)),
               ('EVEN', (0, 1)),
               ('DATA', (0, 1)),
               ('QUAY', (0, 1)),
               ('QUAY', (0, 1))],
 'INDI.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.SOUR.OBJE': [('FILE', (1, None)),
                    ('TITL', (0, 1)),
                    ('FILE', (1, None)),
                    ('TITL', (0, 1))],
 'INDI.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.SSN.ADDR': [('CONT', (0, 3)),
                   ('ADR1', (0, 1)),
                   ('ADR2', (0, 1)),
                   ('ADR3', (0, 1)),
                   ('CITY', (0, 1)),
                   ('STAE', (0, 1)),
                   ('POST', (0, 1)),
                   ('CTRY', (0, 1))],
 'INDI.SSN.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.SSN.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.SSN.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.SSN.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.SSN.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.SSN.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.SSN.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.SSN.SOUR': [('PAGE', (0, 1)),
                   ('EVEN', (0, 1)),
                   ('DATA', (0, 1)),
                   ('QUAY', (0, 1)),
                   ('QUAY', (0, 1))],
 'INDI.SSN.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.SSN.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.SSN.SOUR.OBJE': [('FILE', (1, None)),
                        ('TITL', (0, 1)),
                        ('FILE', (1, None)),
                        ('TITL', (0, 1))],
 'INDI.SSN.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.SSN.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.TITL.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.TITL.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.TITL.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.TITL.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.TITL.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.TITL.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.TITL.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.TITL.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.TITL.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.TITL.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.TITL.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.TITL.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.TITL.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.TITL.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'INDI.WILL.ADDR': [('CONT', (0, 3)),
                    ('ADR1', (0, 1)),
                    ('ADR2', (0, 1)),
                    ('ADR3', (0, 1)),
                    ('CITY', (0, 1)),
                    ('STAE', (0, 1)),
                    ('POST', (0, 1)),
                    ('CTRY', (0, 1))],
 'INDI.WILL.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'INDI.WILL.OBJE.FILE': [('FORM', (1, 1))],
 'INDI.WILL.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'INDI.WILL.PLAC': [('FORM', (0, 1)), ('MAP', (0, 1))],
 'INDI.WILL.PLAC.FONE': [('TYPE', (1, 1))],
 'INDI.WILL.PLAC.MAP': [('LATI', (1, 1)), ('LONG', (1, 1))],
 'INDI.WILL.PLAC.ROMN': [('TYPE', (1, 1))],
 'INDI.WILL.SOUR': [('PAGE', (0, 1)),
                    ('EVEN', (0, 1)),
                    ('DATA', (0, 1)),
                    ('QUAY', (0, 1)),
                    ('QUAY', (0, 1))],
 'INDI.WILL.SOUR.DATA': [('DATE', (0, 1))],
 'INDI.WILL.SOUR.EVEN': [('ROLE', (0, 1))],
 'INDI.WILL.SOUR.OBJE': [('FILE', (1, None)),
                         ('TITL', (0, 1)),
                         ('FILE', (1, None)),
                         ('TITL', (0, 1))],
 'INDI.WILL.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'INDI.WILL.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'NOTE': [('RIN', (0, 1))],
 'NOTE.CHAN': [('DATE', (1, 1))],
 'NOTE.CHAN.DATE': [('TIME', (0, 1))],
 'NOTE.REFN': [('TYPE', (0, 1))],
 'NOTE.SOUR': [('PAGE', (0, 1)),
               ('EVEN', (0, 1)),
               ('DATA', (0, 1)),
               ('QUAY', (0, 1)),
               ('QUAY', (0, 1))],
 'NOTE.SOUR.DATA': [('DATE', (0, 1))],
 'NOTE.SOUR.EVEN': [('ROLE', (0, 1))],
 'NOTE.SOUR.OBJE': [('FILE', (1, None)),
                    ('TITL', (0, 1)),
                    ('FILE', (1, None)),
                    ('TITL', (0, 1))],
 'NOTE.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'NOTE.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'OBJE': [('FILE', (1, None)), ('RIN', (0, 1))],
 'OBJE.CHAN': [('DATE', (1, 1))],
 'OBJE.CHAN.DATE': [('TIME', (0, 1))],
 'OBJE.FILE': [('FORM', (1, 1)), ('TITL', (0, 1))],
 'OBJE.FILE.FORM': [('TYPE', (0, 1))],
 'OBJE.REFN': [('TYPE', (0, 1))],
 'OBJE.SOUR': [('PAGE', (0, 1)),
               ('EVEN', (0, 1)),
               ('DATA', (0, 1)),
               ('QUAY', (0, 1)),
               ('QUAY', (0, 1))],
 'OBJE.SOUR.DATA': [('DATE', (0, 1))],
 'OBJE.SOUR.EVEN': [('ROLE', (0, 1))],
 'OBJE.SOUR.OBJE': [('FILE', (1, None)),
                    ('TITL', (0, 1)),
                    ('FILE', (1, None)),
                    ('TITL', (0, 1))],
 'OBJE.SOUR.OBJE.FILE': [('FORM', (1, 1)), ('FORM', (1, 1))],
 'OBJE.SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1)), ('MEDI', (0, 1))],
 'REPO': [('NAME', (1, 1)), ('RIN', (0, 1))],
 'REPO.ADDR': [('CONT', (0, 3)),
               ('ADR1', (0, 1)),
               ('ADR2', (0, 1)),
               ('ADR3', (0, 1)),
               ('CITY', (0, 1)),
               ('STAE', (0, 1)),
               ('POST', (0, 1)),
               ('CTRY', (0, 1))],
 'REPO.CHAN': [('DATE', (1, 1))],
 'REPO.CHAN.DATE': [('TIME', (0, 1))],
 'REPO.REFN': [('TYPE', (0, 1))],
 'SOUR': [('DATA', (0, 1)),
          ('AUTH', (0, 1)),
          ('TITL', (0, 1)),
          ('ABBR', (0, 1)),
          ('PUBL', (0, 1)),
          ('TEXT', (0, 1)),
          ('RIN', (0, 1))],
 'SOUR.CHAN': [('DATE', (1, 1))],
 'SOUR.CHAN.DATE': [('TIME', (0, 1))],
 'SOUR.DATA': [('AGNC', (0, 1))],
 'SOUR.DATA.EVEN': [('DATE', (0, 1)), ('PLAC', (0, 1))],
 'SOUR.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'SOUR.OBJE.FILE': [('FORM', (1, 1))],
 'SOUR.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'SOUR.REFN': [('TYPE', (0, 1))],
 'SOUR.REPO.CALN': [('MEDI', (0, 1))],
 'SUBM': [('NAME', (1, 1)), ('LANG', (0, 3)), ('RFN', (0, 1)), ('RIN', (0, 1))],
 'SUBM.ADDR': [('CONT', (0, 3)),
               ('ADR1', (0, 1)),
               ('ADR2', (0, 1)),
               ('ADR3', (0, 1)),
               ('CITY', (0, 1)),
               ('STAE', (0, 1)),
               ('POST', (0, 1)),
               ('CTRY', (0, 1))],
 'SUBM.CHAN': [('DATE', (1, 1))],
 'SUBM.CHAN.DATE': [('TIME', (0, 1))],
 'SUBM.OBJE': [('FILE', (1, None)), ('TITL', (0, 1))],
 'SUBM.OBJE.FILE': [('FORM', (1, 1))],
 'SUBM.OBJE.FILE.FORM': [('MEDI', (0, 1))],
 'SUBN': [('SUBM', (0, 1)),
          ('FAMF', (0, 1)),
          ('TEMP', (0, 1)),
          ('ANCE', (0, 1)),
          ('DESC', (0, 1)),
          ('ORDI', (0, 1)),
          ('RIN', (0, 1))],
 'SUBN.CHAN': [('DATE', (1, 1))],
 'SUBN.CHAN.DATE': [('TIME', (0, 1))]}
